// swift-tools-version: 5.5

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Spectrodraw",
    platforms: [
        .iOS("15.2")
    ],
    products: [
        .iOSApplication(
            name: "Spectrodraw",
            targets: ["AppModule"],
            bundleIdentifier: "AbigailDeMicco.Spectrodraw",
            teamIdentifier: "W86559Y4YC",
            displayVersion: "1.0",
            bundleVersion: "1",
            iconAssetName: "AppIcon",
            accentColorAssetName: "AccentColor",
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .microphone(purposeString: "App needs to access to your Microphone to show spectrogram"),
                .photoLibraryAdd(purposeString: "App needs to access to your Photo Library to save the drawing")
            ]
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: ".",
            resources: [
                .process("Resources")
            ]
        )
    ]
)